---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
    spec:
      containers:
      - name: currencyservice-app
        image: gcr.io/google-samples/microservices-demo/currencyservice
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"

